import { useEffect } from 'react'
import Head from 'next/head'
import { Presentation } from '../components/Presentation/Presentation'
import { Projects } from '../components/Projects/Projects'
import { Footer } from '../components/Footer/Footer'
import { Header } from '../components/Header/Header';
import Skill from '../components/Skill/Skill';
import { Experience } from '../components/Experience/Experience';

export default function Home() {

  return (
    <div >
      <Head>
        <title>Alfonso 👨‍💻 | Portafolio </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="Main">
        <Header />
        <Presentation />
        <Skill />
        <Projects />
        <Experience />
      </main>

      <Footer />
    </div>
  )
}
